name: 'Build'

on:
  push:
    branches:
      - master
    paths:
      - "*.js"
      - "package*.json"
      - "Dockerfile"
      - ".github/workflows/dockerimage.yml"
  workflow_dispatch:
  pull_request:
    branches: [ master ] 

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - 
        uses: actions/checkout@v4

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_HUB_IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/nut-http
          flavor: |
            latest=true
          tags: |
              type=schedule
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=edge
              type=ref,event=pr
              type=sha
      -
        name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}