name: '[builder] CI for releases'

on:
  push:
    branches:
      - master
    paths:
      - "*.js"
      - "package*.json"
      - "Dockerfile"
      - ".github/workflows/dockerimage.yml"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build on ARMv7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: if [ "${GITHUB_REF#refs/*/}" == "master" ]; then echo ::set-output name=branch::latest; else echo ::set-output name=branch::${GITHUB_REF#refs/*/}; fi
      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Build docker on armv7 and push to Dockerhub
        uses: uraimo/run-on-arch-action@v1.0.8
        id: runcmd
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            docker build
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/nut-http:${{ steps.vars.outputs.branch }}
